
name: Build & Push docker image

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
      - name: "Extract git ref"
        id: extract_ref
        shell: bash
        run: echo "git_ref_name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "Loki-Afro"
          password: ${{ secrets.GH_REGISTRY_SECRET }}
          repository: kaffeekrone/mail-drop
          tags: ${{ env.git_ref_name }}
