
name: Build & Push docker image

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v4
      - name: "Extract git ref"
        id: extract_ref
        shell: bash
        run: echo "git_ref_name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.git_ref_name }}
